import numpy as np
ar=np.array([8,9,1,0,40,6])
print(ar)
print(ar.dtype)
ar=np.array([9.7,8.1],dtype=np.int64)
print(ar)
print(ar.dtype)
ar=np.array(['Hello','Samhith'])
print(ar)
print(ar.dtype)
ar=np.array([8,9,1,0,40,6])
ar.sort()
print(ar)
ar.sort()
print(ar[::-1])
ar=np.array([8,9,1,0,40,6])
print(ar.shape)
ar=np.array([[8,9,1],[0,40,6]])
print(ar.shape)
ar=np.array([8,9,1,0,40,6])
for x in ar:
    print(x)
x=np.where(ar==40)
print(x)
from numpy import random
x=random.randint(5)#0 to 4
print(x)
ar1=np.array([3,8,2])
ar2=np.array([0,9,4])
print(np.add(ar1,ar2))
print(np.subtract(ar1,ar2))
print(np.multiply(ar1,ar2))
print(np.divide(ar1,ar2))
print(ar1+ar2)
print(np.add(ar1,ar2))
print(np.concatenate((ar1,ar2)))
